name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run Bandit
        if: github.event_name == 'pull_request'
        run: poetry run bandit -r src/
      - name: Run Safety
        if: github.event_name == 'pull_request'
        run: poetry run safety check
      - name: Run tests
        run: poetry run pytest -q
